services:
  oas-api:
    container_name: oas-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - config.env
    networks:
      - oas
      - npm-network

networks:
  oas:
    external: true
  npm-network:
    external: true
