services:
  app:
    build: .
    ports:
      - "127.0.0.1:3456:3456"
    restart: always
    env_file:
      - config.env
    volumes:
      - ./run.log:/app/run.log
    command: ["sh", "-c", "npm run prod"]