services:
  app:
    container_name: oas-api-${CONTAINER_NUMBER:-1}
    build: .
    image: oas-api:latest
    ports:
      - "127.0.0.1:3456:3456"
      - "[::1]:3456:3456"
    restart: always
    env_file:
      - config.env
    networks:
      - oas
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  oas:
    external: true