name: Deploy To Production

# Trigger Points
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          SECRET_PATH: ${{secrets.SECRET_PATH}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: SECRET_PATH
          script: "cd ~/server/mail && sh ./.scripts/live.sh"